VECTOR_SIZE = 512
DATABASE_PATH = "database.db"
ANNOY_INDEX_PATH = "index.ann"
BACK_UP_PATH = "backups"
IMAGES_UPLOAD_PATH = "static/uploads/"
USER_UPLOAD_FOLDER = "static/user/uploads/"
USER_SEARCH_IMAGE = "static/user/search_image/"
SQL_SCRIPT_PATH = "sql/schema.sql" 
MODEL_DOWNLOAD_PATH = "models"
NUM_OF_NEAREST_NEIGHBORS = 10
SIMLARITY_METRIC = "angular"
ANNOY_METRIC= "angular"